name: Test docker container file
on:
  push:
    branches:
    - main
    paths: [ hello-world-docker_action/** ]
  workflow_dispatch:

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Run container
        id: hello-action
        uses: ./hellow-world-docker-action
        with:
          who-to-greet: "@nikolina"

      - name: Time display
        run: echo "Time was ${{ steps.hello-action.outputs.time }}"
